// APP
export const UPDATE_NAVIGATION_REQUEST = 'UPDATE_NAVIGATION_REQUEST';
export const UPDATE_NAVIGATION_SUCCESS = 'UPDATE_NAVIGATION_SUCCESS';

export const REGISTER_TOKEN_REQUEST = 'REGISTER_TOKEN_REQUEST';
export const REGISTER_TOKEN_SUCCESS = 'REGISTER_TOKEN_SUCCESS';
export const REGISTER_TOKEN_FAILURE = 'REGISTER_TOKEN_FAILURE';

export const SEND_FEEDBACK_REQUEST = 'SEND_FEEDBACK_REQUEST';
export const SEND_FEEDBACK_SUCCESS = 'SEND_FEEDBACK_SUCCESS';
export const SEND_FEEDBACK_FAILURE = 'SEND_FEEDBACK_FAILURE';

// AUTH
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

// USERS
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const ADD_USER_TO_FAVORITE_REQUEST = 'ADD_USER_TO_FAVORITE_REQUEST';
export const ADD_USER_TO_FAVORITE_SUCCESS = 'ADD_USER_TO_FAVORITE_SUCCESS';
export const ADD_USER_TO_FAVORITE_FAILURE = 'ADD_USER_TO_FAVORITE_FAILURE';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const GET_USERS_REFRESH_REQUEST = 'GET_USERS_REFRESH_REQUEST';
export const GET_USERS_REFRESH_SUCCESS = 'GET_USERS_REFRESH_SUCCESS';

export const GET_USERS_MORE_REQUEST = 'GET_USERS_MORE_REQUEST';
export const GET_USERS_MORE_SUCCESS = 'GET_USERS_MORE_SUCCESS';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

// CHAT
export const GET_CHATS_REQUEST = 'GET_CHATS_REQUEST';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const GET_CHATS_FAILURE = 'GET_CHATS_FAILURE';

export const GET_CHATS_REFRESH_REQUEST = 'GET_CHATS_REFRESH_REQUEST';
export const GET_CHATS_REFRESH_SUCCESS = 'GET_CHATS_REFRESH_SUCCESS';

export const GET_CHATS_MORE_REQUEST = 'GET_CHATS_MORE_REQUEST';
export const GET_CHATS_MORE_SUCCESS = 'GET_CHATS_MORE_SUCCESS';

export const GET_CHAT_MESSAGES_REQUEST = 'GET_CHAT_MESSAGES_REQUEST';
export const GET_CHAT_MESSAGES_SUCCESS = 'GET_CHAT_MESSAGES_SUCCESS';
export const GET_CHAT_MESSAGES_FAILURE = 'GET_CHAT_MESSAGES_FAILURE';

export const GET_CHAT_MESSAGES_MORE_REQUEST = 'GET_CHAT_MESSAGES_MORE_REQUEST';
export const GET_CHAT_MESSAGES_MORE_SUCCESS = 'GET_CHAT_MESSAGES_MORE_SUCCESS';

export const UPDATE_CHAT = 'UPDATE_CHAT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SOCKET_ERROR = 'SOCKET_ERROR';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const VIEW_MESSAGES = 'VIEW_MESSAGES';
export const UPDATE_VIEWED_MESSAGES = 'UPDATE_VIEWED_MESSAGES';
export const UPDATE_UNREAD_MESSAGES = 'UPDATE_UNREAD_MESSAGES';
export const DELETE_MESSAGES = 'DELETE_MESSAGES';
export const UPDATE_DELETE_MESSAGES = 'UPDATE_DELETE_MESSAGES';

export const JOIN_TO_CHAT_REQUEST = 'JOIN_TO_CHAT_REQUEST';
export const JOIN_TO_CHAT_SUCCESS = 'JOIN_TO_CHAT_SUCCESS';
export const BACKGROUND_JOIN_TO_CHAT_SUCCESS =
  'BACKGROUND_JOIN_TO_CHAT_SUCCESS';
export const JOIN_TO_CHAT_FAILURE = 'JOIN_TO_CHAT_FAILURE';

export const CLEAR_ACTIVE_CHAT = 'CLEAR_ACTIVE_CHAT';

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAILURE = 'DELETE_CHAT_FAILURE';

export const TOGGLE_MESSAGE_CONTEXT_MENU = 'TOGGLE_MESSAGE_CONTEXT_MENU';

// Collaborations
export const GET_COLLABORATIONS_REQUEST = 'GET_COLLABORATIONS_REQUEST';
export const GET_COLLABORATIONS_SUCCESS = 'GET_COLLABORATIONS_SUCCESS';
export const GET_COLLABORATIONS_FAILURE = 'GET_COLLABORATIONS_FAILURE';

export const GET_COLLABORATIONS_REFRESH_REQUEST =
  'GET_COLLABORATIONS_REFRESH_REQUEST';
export const GET_COLLABORATIONS_REFRESH_SUCCESS =
  'GET_COLLABORATIONS_REFRESH_SUCCESS';

export const GET_COLLABORATIONS_MORE_REQUEST =
  'GET_COLLABORATIONS_MORE_REQUEST';
export const GET_COLLABORATIONS_MORE_SUCCESS =
  'GET_COLLABORATIONS_MORE_SUCCESS';

export const GET_USER_COLLABORATIONS_REQUEST =
  'GET_USER_COLLABORATIONS_REQUEST';
export const GET_USER_COLLABORATIONS_SUCCESS =
  'GET_USER_COLLABORATIONS_SUCCESS';
export const GET_USER_COLLABORATIONS_FAILURE =
  'GET_USER_COLLABORATIONS_FAILURE';

export const GET_USER_COLLABORATIONS_REFRESH_REQUEST =
  'GET_USER_COLLABORATIONS_REFRESH_REQUEST';
export const GET_USER_COLLABORATIONS_REFRESH_SUCCESS =
  'GET_USER_COLLABORATIONS_REFRESH_SUCCESS';

export const GET_USER_COLLABORATIONS_MORE_REQUEST =
  'GET_USER_COLLABORATIONS_MORE_REQUEST';
export const GET_USER_COLLABORATIONS_MORE_SUCCESS =
  'GET_USER_COLLABORATIONS_MORE_SUCCESS';

export const GET_COLLABORATION_REQUEST = 'GET_COLLABORATION_REQUEST';
export const GET_COLLABORATION_SUCCESS = 'GET_COLLABORATION_SUCCESS';
export const GET_COLLABORATION_FAILURE = 'GET_COLLABORATION_FAILURE';

export const JOIN_TO_COLLABORATION_REQUEST = 'JOIN_TO_COLLABORATION_REQUEST';
export const JOIN_TO_COLLABORATION_SUCCESS = 'JOIN_TO_COLLABORATION_SUCCESS';
export const JOIN_TO_COLLABORATION_FAILURE = 'JOIN_TO_COLLABORATION_FAILURE';

export const ADD_COLLABORATION_TO_FAVORITE_REQUEST =
  'ADD_COLLABORATION_TO_FAVORITE_REQUEST';
export const ADD_COLLABORATION_TO_FAVORITE_SUCCESS =
  'ADD_COLLABORATION_TO_FAVORITE_SUCCESS';
export const ADD_COLLABORATION_TO_FAVORITE_FAILURE =
  'ADD_COLLABORATION_TO_FAVORITE_FAILURE';

export const CLEAR_COLLABORATION = 'CLEAR_COLLABORATION';

export const CREATE_COLLABORATION_REQUEST = 'CREATE_COLLABORATION_REQUEST';
export const CREATE_COLLABORATION_SUCCESS = 'CREATE_COLLABORATION_SUCCESS';
export const CREATE_COLLABORATION_FAILURE = 'CREATE_COLLABORATION_FAILURE';

export const GET_MY_COLLABORATIONS_REQUEST = 'GET_MY_COLLABORATIONS_REQUEST';
export const GET_MY_COLLABORATIONS_SUCCESS = 'GET_MY_COLLABORATIONS_SUCCESS';
export const GET_MY_COLLABORATIONS_FAILURE = 'GET_MY_COLLABORATIONS_FAILURE';

export const GET_MY_COLLABORATIONS_REFRESH_REQUEST =
  'GET_MY_COLLABORATIONS_REFRESH_REQUEST';
export const GET_MY_COLLABORATIONS_REFRESH_SUCCESS =
  'GET_MY_COLLABORATIONS_REFRESH_SUCCESS';

export const GET_MY_COLLABORATIONS_MORE_REQUEST =
  'GET_MY_COLLABORATIONS_MORE_REQUEST';
export const GET_MY_COLLABORATIONS_MORE_SUCCESS =
  'GET_MY_COLLABORATIONS_MORE_SUCCESS';

export const RATE_COLLABORATION_REQUEST = 'RATE_COLLABORATION_REQUEST';
export const RATE_COLLABORATION_SUCCESS = 'RATE_COLLABORATION_SUCCESS';
export const RATE_COLLABORATION_FAILURE = 'RATE_COLLABORATION_FAILURE';

export const UPDATE_COLLABORATION_REQUEST = 'UPDATE_COLLABORATION_REQUEST';
export const UPDATE_COLLABORATION_SUCCESS = 'UPDATE_COLLABORATION_SUCCESS';
export const UPDATE_COLLABORATION_FAILURE = 'UPDATE_COLLABORATION_FAILURE';

export const DELETE_COLLABORATION_REQUEST = 'DELETE_COLLABORATION_REQUEST';
export const DELETE_COLLABORATION_SUCCESS = 'DELETE_COLLABORATION_SUCCESS';
export const DELETE_COLLABORATION_FAILURE = 'DELETE_COLLABORATION_FAILURE';

// Upload
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

export const UPLOAD_ATTACHMENT = 'UPLOAD_ATTACHMENT';
export const UPLOAD_ATTACHMENT_SUCCESS = 'UPLOAD_ATTACHMENT_SUCCESS';
export const UPLOAD_ATTACHMENT_FAILURE = 'UPLOAD_ATTACHMENT_FAILURE';

export const DOWNLOAD_FILE_AND_SAVE = 'DOWNLOAD_FILE_AND_SAVE';

// Requests
export const GET_JOIN_COLLABORATION_REQUESTS_REQUEST =
  'GET_JOIN_COLLABORATION_REQUESTS_REQUEST';
export const GET_JOIN_COLLABORATION_REQUESTS_SUCCESS =
  'GET_JOIN_COLLABORATION_REQUESTS_SUCCESS';
export const GET_JOIN_COLLABORATION_REQUESTS_FAILURE =
  'GET_JOIN_COLLABORATION_REQUESTS_FAILURE';

export const GET_JOIN_COLLABORATION_REQUESTS_REFRESH_REQUEST =
  'GET_JOIN_COLLABORATION_REQUESTS_REFRESH_REQUEST';
export const GET_JOIN_COLLABORATION_REQUESTS_REFRESH_SUCCESS =
  'GET_JOIN_COLLABORATION_REQUESTS_REFRESH_SUCCESS';

export const CHANGE_STATUS_REQUEST_REQUEST = 'CHANGE_STATUS_REQUEST_REQUEST';
export const CHANGE_STATUS_REQUEST_SUCCESS = 'CHANGE_STATUS_REQUEST_SUCCESS';
export const CHANGE_STATUS_REQUEST_FAILURE = 'CHANGE_STATUS_REQUEST_FAILURE';

export const UPDATE_UNVIEWED_REQUESTS = 'UPDATE_UNVIEWED_REQUESTS';
export const NEW_JOIN_COLLABORATION_REQUEST = 'NEW_JOIN_COLLABORATION_REQUEST';

export const CANCEL_JOIN_REQUEST_REQUEST = 'CANCEL_JOIN_REQUEST_REQUEST';
export const CANCEL_JOIN_REQUEST_SUCCESS = 'CANCEL_JOIN_REQUEST_SUCCESS';
export const CANCEL_JOIN_REQUEST_FAILURE = 'CANCEL_JOIN_REQUEST_FAILURE';

// Search
export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const CHANGE_FILTER = 'CHANGE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';

// Review
export const GET_USERS_REVIEWS_REQUEST = 'GET_USERS_REVIEWS_REQUEST';
export const GET_USERS_REVIEWS_SUCCESS = 'GET_USERS_REVIEWS_SUCCESS';
export const GET_USERS_REVIEWS_FAILURE = 'GET_USERS_REVIEWS_FAILURE';

export const GET_USERS_REVIEWS_REFRESH_REQUEST =
  'GET_USERS_REVIEWS_REFRESH_REQUEST';
export const GET_USERS_REVIEWS_REFRESH_SUCCESS =
  'GET_USERS_REVIEWS_REFRESH_SUCCESS';

export const GET_USERS_REVIEWS_MORE_REQUEST = 'GET_USERS_REVIEWS_MORE_REQUEST';
export const GET_USERS_REVIEWS_MORE_SUCCESS = 'GET_USERS_REVIEWS_MORE_SUCCESS';

// Complaint
export const CREATE_COMPLAINT = 'CREATE_COMPLAINT';
export const CREATE_COMPLAINT_SUCCESS = 'CREATE_COMPLAINT_SUCCESS';
export const CREATE_COMPLAINT_FAIL = 'CREATE_COMPLAINT_FAIL';

// Quiz
export const SEND_QUIZ = 'SEND_QUIZ';
export const SEND_QUIZ_INFO = 'SEND_QUIZ_INFO';

// Auth profile initial request
export const AUTH_INITIAL_PROFILE_REQUEST = 'AUTH_INITIAL_PROFILE_REQUEST';
