export const GET_POTENTIAL_PARTNERS_REQUEST = 'GET_POTENTIAL_PARTNERS_REQUEST';
export const GET_POTENTIAL_PARTNERS_REFRESH_REQUEST =
  'GET_POTENTIAL_PARTNERS_REFRESH_REQUEST';
export const GET_POTENTIAL_PARTNERS_MORE_REQUEST =
  'GET_POTENTIAL_PARTNERS_MORE_REQUEST';
export const GET_POTENTIAL_PARTNERS_SUCCESS = 'GET_POTENTIAL_PARTNERS_SUCCESS';
export const GET_POTENTIAL_PARTNERS_REFRESH_SUCCESS =
  'GET_POTENTIAL_PARTNERS_REFRESH_SUCCESS';
export const GET_POTENTIAL_PARTNERS_MORE_SUCCESS =
  'GET_POTENTIAL_PARTNERS_MORE_SUCCESS';
export const GET_POTENTIAL_PARTNERS_FAILURE = 'GET_POTENTIAL_PARTNERS_FAILURE';

export const POTENTIAL_PARTNERS_COLLABORATE = 'POTENTIAL_PARTNERS_COLLABORATE';
