export const IN_APP_PURCHASE_CONNECTION_REQUEST =
  'IN_APP_PURCHASE_CONNECTION_REQUEST';
export const IN_APP_PURCHASE_CONNECTION_SUCCESS =
  'IN_APP_PURCHASE_CONNECTION_SUCCESS';
export const IN_APP_PURCHASE_CONNECTION_FAILURE =
  'IN_APP_PURCHASE_CONNECTION_FAILURE';

export const GET_IAP_SUBSCRIPTIONS_LIST_REQUEST =
  'GET_IAP_SUBSCRIPTIONS_LIST_REQUEST';
export const GET_IAP_SUBSCRIPTIONS_LIST_SUCCESS =
  'GET_IAP_SUBSCRIPTIONS_LIST_SUCCESS';
export const GET_IAP_SUBSCRIPTIONS_LIST_FAILURE =
  'GET_IAP_SUBSCRIPTIONS_LIST_FAILURE';

export const GET_IAP_PRODUCTS_LIST_REQUEST = 'GET_IAP_PRODUCTS_LIST_REQUEST';
export const GET_IAP_PRODUCTS_LIST_SUCCESS = 'GET_IAP_PRODUCTS_LIST_SUCCESS';
export const GET_IAP_PRODUCTS_LIST_FAILURE = 'GET_IAP_PRODUCTS_LIST_FAILURE';

// actions for handling payment in store
export const HANDLE_PURCHASE_REQUEST = 'HANDLE_PURCHASE_REQUEST';
export const HANDLE_PURCHASE_SUCCESS = 'HANDLE_PURCHASE_SUCCESS';
export const HANDLE_PURCHASE_FAILURE = 'HANDLE_PURCHASE_FAILURE';

// actions for handling payment AFTER store
// involving HH backend and finishing store transaction
export const HANDLE_PURCHASE_PAYMENT_REQUEST =
  'HANDLE_PURCHASE_PAYMENT_REQUEST';
export const HANDLE_PURCHASE_PAYMENT_SUCCESS =
  'HANDLE_PURCHASE_PAYMENT_SUCCESS';
export const HANDLE_PURCHASE_PAYMENT_FAILURE =
  'HANDLE_PURCHASE_PAYMENT_FAILURE';

// actions for downgrading old premium (stripe) to basic
export const DONWGRADE_OLD_PREMIUM_TO_BASIC_REQUEST =
  'DONWGRADE_OLD_PREMIUM_TO_BASIC_REQUEST';
export const DONWGRADE_OLD_PREMIUM_TO_BASIC_SUCCESS =
  'DONWGRADE_OLD_PREMIUM_TO_BASIC_SUCCESS';
export const DONWGRADE_OLD_PREMIUM_TO_BASIC_FAILURE =
  'DONWGRADE_OLD_PREMIUM_TO_BASIC_FAILURE';

export const CHANGE_PAYMENT_HOST = 'CHANGE_PAYMENT_HOST';
